---
Name: approutes
After:
  - '#rootroutes'
  - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    '': '->dashboard'
    'dashboard': 'App\Controllers\DashboardController'
    'calendar//$Action/$ID/$Name': 'App\Controllers\CalendarController'
    'ics//$Action/$ID/$Name': 'App\Controllers\ICSController'
    'notices//$Action/$ID/$Name': 'App\Controllers\NoticesController'
    'profile//$Action/$ID/$Name': 'App\Controllers\ProfileController'
    'registration//$Action/$ID/$Name': 'App\Controllers\RegistrationController'
    'suggestionbox//$Action/$ID/$Name': 'App\Controllers\SuggestionBoxController'
    'food//$Action/$ID/$Name': 'App\Controllers\FoodController'
    'links//$Action/$ID/$Name': 'App\Controllers\LinksController'
