---
Name: approutes
After:
  - '#rootroutes'
  - '#coreroutes'
---
SilverStripe\Control\Director:
  rules:
    'dashboard': 'App\Pages\DashboardPageController'
    '': 'App\Pages\DashboardPageController'
    'calendar//$Action/$ID/$Name': 'App\Pages\CalendarPageController'
    'ics//$Action/$ID/$Name': 'App\Pages\ICSPageController'
    'notices//$Action/$ID/$Name': 'App\Pages\NoticesPageController'
    'profile//$Action/$ID/$Name': 'App\Pages\ProfilePageController'
    'registration//$Action/$ID/$Name': 'App\Pages\RegistrationPageController'
    'suggestionbox//$Action/$ID/$Name': 'App\Pages\SuggestionBoxPageController'
